kind: pipeline
name: default
steps:
- name: docker
  image: plugins/docker
  settings:
    registry: git.jonb.io
    dry_run: false
    username: jblu
    password: 
      from_secret: gittea_drone
    repo: git.jonb.io/jblu/crane
    tags:
    - latest
  when:
    branch:
      - main
    event:
      - push
      - pull_request
- name: docker-test
  image: plugins/docker
  settings:
    registry: git.jonb.io
    dry_run: false
    username: jblu
    password: 
      from_secret: gittea_drone
    repo: git.jonb.io/jblu/crane
    tags:
    - dev
  when:
    branch:
      - dev*
    event:
      - push
      - pull_request
- name: test-main
  image: git.jonb.io/jblu/crane:latest
  environment:
    CRANE_HOST:
      from_secret: CRANE_HOST
    CRANE_PORT:
      from_secret: CRANE_PORT
    CRANE_ENDPOINT:
      from_secret: CRANE_ENDPOINT
  commands:
  - echo $CRANE_HOST
  - echo $CRANE_PORT
  - echo $CRANE_ENDPOINT
  - python test_crane.py
  when:
    branch:
      - main
    event:
      - push
      - pull_request
- name: test-dev
  image: git.jonb.io/jblu/crane:dev
  environment:
    CRANE_HOST:
      from_secret: CRANE_HOST
    CRANE_PORT:
      from_secret: CRANE_PORT
    CRANE_ENDPOINT:
      from_secret: CRANE_ENDPOINT
  commands:
  - echo $CRANE_HOST
  - echo $CRANE_PORT
  - echo $CRANE_ENDPOINT
  - python test_crane.py
  when:
    branch:
      - dev*
    event:
      - push
      - pull_request